# Generated by Django 3.2.12 on 2022-04-01 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'new'), ('assigned', 'assigned'), ('in_process', 'in_process'), ('done', 'done')], default='new', max_length=25)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='service.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
