# Generated by Django 3.2.12 on 2022-04-10 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_servicetype_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetype',
            old_name='icon',
            new_name='logo',
        ),
    ]
